[package]
name = "lookup"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
colored = "2.0.4"
crossterm = "0.29.0"
itertools = "0.11.0"
rand = "0.8.5"
regex = "1.11.0"
serde_json = "1.0.141"
rustyline = "17.0.2"